/*global  _, $*/
"use strict";

/**
 * @module fmk/views/SearchView
 */

// Filename: views/search-view.js
var NotImplementedException = require('../helpers/custom_exception').NotImplementedException;
var ErrorHelper = require('../helpers/error_helper');
var form_helper = require('../helpers/form_helper');
var ModelValidator = require('../helpers/model_validation_promise');
var CoreView = require('./core-view');
var errorHelper = require('../helpers/error_helper');
var backboneNotification = require("../helpers/backbone_notification");

var SearchView;
/**
 * SearchView
 * @class
 * @alias module:fmk/views/SearchView
 * @augments module:fmk/views/CoreView
 */
SearchView = CoreView.extend({
  tagName: 'div',
  className: 'searchView',
  ResultsView: undefined,
  Results: undefined,
  search: undefined,
  resultsSelector: 'div#results',
  isMoreCriteria: false,

  /**
   * Default options of the search view.
   * @enum
   * @override
   */
  defaultOptions: {
    /**
     * This options is use in order to not have a tag container generated by Backbone around the view.
     * (inherited from fmk.views.CoreView, default value : false)
     */
    isElementRedefinition: CoreView.prototype.defaultOptions.isElementRedefinition,
    /**
     * If criteria is readonly.
     * (default value: false)
     */
    isReadOnly: false,
    /**
     * Indicate if references values are ready.
     * (inherited from fmk.views.CoreView, default value : true)
     */
    isReadyReferences: CoreView.prototype.defaultOptions.isReadyReferences,
    /**
     * Refresh on input change.
     * (default value: true)
     */
    isRefreshSearchOnInputChange: true,
    /**
     * If search is triggered on load.
     * (default value: false)
     */
    isSearchTriggered: false,
    /**
     * Activate debug information.
     * (inherited from fmk.views.CoreView, default value : false)
     */
    DEBUG: CoreView.prototype.defaultOptions.DEBUG
  },

  /**
   * Initialization of the SearchView.
   * @param options
   * @override
   */
  initialize: function initializeSearchView(options) {
    options = options || {};
    // Call the initialize function of the core view.
    CoreView.prototype.initialize.call(this, options);
    this.isSearchTriggered = options.isSearchTriggered;
    this.stopListening(this.model, "reset");
    this.isReadOnly = options.isReadOnly;
    this.model.set({
      isCriteriaReadonly: false
    }, {
      silent: true
    });

    // Init results collection
    if (!this.Results) {
      throw new NotImplementedException('Your view should have a Reference to the result collection in the Results property', this);
    }
    if (!this.ResultsView) {
      throw new NotImplementedException('Your view should have a Reference to the ResultsView in order to display the results', this);
    }
    this.searchResults = new this.Results();
    // Initialization of the result view
    this.searchResultsView = new this.ResultsView({
      model: this.searchResults,
      criteria: this.model,
      searchView: this,
      isSearchTriggered: false
    });
    // Handle the clear criteria action
    this.listenTo(this.model, 'change', this.render);
    this.listenTo(this.searchResultsView, 'results:fetchDemand', function () {
      this.runSearch(null, {
        isFormBinded: false
      });
    });
    this.listenTo(this.searchResultsView, 'listview:lineSelected', function () {
      $('.collapse', this.$el).collapse('hide');
    });
    var currentView = this;
    this.session.get().then(function (crit) {
      // Restore the criteria if save into the session.
      if (crit !== undefined && crit !== null && crit.pageInfo !== undefined && crit.pageInfo !== null) {
        currentView.model.set(crit.criteria, {
          silent: false
        });
        currentView.searchResults.setPageInfo(crit.pageInfo);
        currentView.isSearchTriggered = true;
      }
      // If the search has to be triggered, trigger it.
      if (currentView.isSearchTriggered) {
        currentView.runSearch(null, {
          isFormBinded: false
        });
      }
    }, function (error) {
      errorHelper.manageResponseErrors(error);
    });

    if (this.opts.isRefreshSearchOnInputChange) {
      this.events = _.extend({}, this.events, this.defaultEvents, this.refreshSearchOnInputChangeEvents);
    }
    this.delegateEvents();
  },

  events: {
    "submit form": 'runSearch', // Launch the search.
    "click button.btnReset": 'clearSearchCriteria', // Reset all the criteria.
    "click button.btnEditCriteria": 'editCriteria', // Deal with the edit mode.
    "click button.toogleCriteria": 'toogleMoreCriteria', // Deal with the more / less criteria.
    "click .panel-heading": "toogleCollapse",
    "click button.btnCreate": "create"
  },

  refreshSearchOnInputChangeEvents: {
    "change [data-refresh]  input:not([noRefresh])": "runSearch",
    "change [data-refresh] select:not([noRefresh]) ": "runSearch"
  },

  // Change the fact that the view is in the mode mode or less criteria.
  toogleMoreCriteria: function toogleMoreCriteria() {
    this.isMoreCriteria = !this.isMoreCriteria;
    form_helper.formModelBinder({
      inputs: $('input', this.$el)
    }, this.model);
    this.render();
  },
  /**
   * Get the JSON to attach to the template
   * @returns {*|string}
   * @override
   * @todo Same code as CoreView
   */
  getRenderData: function getRenderDataSearchView() {
    var jsonToRender = this.model.toJSON();
    if (this.model.references) {
      _.extend(jsonToRender, this.model.references);
    }
    return jsonToRender;
  },
  /**
   * Change criteria to edit mode.
   */
  editCriteria: function editCriteriaSearchView() {
    this.model.set({
      isCriteriaReadonly: false
    });
  },
  /**
   * Create result view.
   */
  create: function createNavigateSearchView() {
    this.searchResultsView.create();
  },
  /**
   * Display search succeed.
   * @param jsonResponse
   */
  searchSuccess: function searchSuccessSearchView(jsonResponse) {
    this.searchResults.setTotalRecords(jsonResponse.totalRecords);
    this.searchResults.reset(jsonResponse.values);
  },
  /**
   * Display search errors.
   * @param response
   */
  searchError: function searchErrorSearchView(response) {
    this.searchResults.reset([]);
    ErrorHelper.manageResponseErrors(response, {
      isDisplay: true,
      model: this.model
    });
  },
  /**
   * Get the criteria from the view.
   * @return {object} A clone of the json model.
   */
  getCriteria: function getCriteriaSearchView () {
    return _.clone(this.model.toJSON());
  },
  /**
   * Run the search when it is trigerred by the formaction or the session saved criteria.
   * @param  {object} event   - jQuery event.
   * @param  {object} options - Options for the running search.
   * @return {undefined}
   */
  runSearch: function runSearchSearchView(event, options) {
    var searchButton;
    var isEvent = event !== undefined && event !== null;
    if (isEvent) {
      event.preventDefault();
      searchButton = $("button[type=submit]", event.target); // Retrieving the button that triggered the search
    }
    options = options || {};
    var isFormBinded = options.isFormBinded === undefined ? true : options.isFormBinded;
    // Bind form fields on model
    if (isFormBinded) {
      form_helper.formModelBinder({
        inputs: $('input', this.$el),
        options: $('select', this.$el)
      }, this.model);
    }
    // Render loading inside the search results:
    this.searchResultsView.opts.isReadyResultsData = false;
    this.searchResultsView.render();
    var currentView = this;
    ModelValidator
        .validate(this.model)
        .then(function(model) {
          currentView.model.unsetErrors({
            silent: false
          });
          var criteria = currentView.getCriteria();
          var pageInfo = currentView.searchResults.pageInfo();

          if (isEvent) {
            pageInfo.currentPage = 1;
          }
          if (!currentView.search) {
            throw new NotImplementedException('The search property of this view is not defined, the search cannot be launched.', this);
          }
          currentView
              .search(criteria, pageInfo)
              .then(function success(jsonResponse) {
                // Save the criteria in session.
                currentView.searchResultsView.opts.isReadyResultsData = true;
                currentView.searchResultsView.isSearchTriggered = true;
                currentView.searchResults.setPageInfo(pageInfo);
                currentView.session.save({
                  criteria: criteria,
                  pageInfo: pageInfo
                }).then(function (s) {
                  backboneNotification.clearNotifications();
                  return currentView.searchSuccess(jsonResponse);
                });
              }).then(null, function error(errorResponse) {
                currentView.searchResultsView.opts.isReadyResultsData = true;
                currentView.searchError(errorResponse);
              }).then(function resetButton() {
                if (searchButton) {
                  searchButton.button('reset');
                }
              });
        }).then(null, function error(errors) {
          currentView.model.setErrors(errors);
          if (searchButton) {
            searchButton.button('reset');
          }
        });

    if (this.isReadOnly) {
      this.model.set({
        isCriteriaReadonly: true
      });
    }
  },
  /**
   * Reset all the criteria. Handle reset button click.
   * @param event
   */
  clearSearchCriteria: function clearSearchCriteria(event) {
    event.preventDefault();
    this.model.clear();
    var currentView = this;
    this.session.get().then(function (item) {
      if (item !== null) {
        currentView.session.delete().then(function(item){}); // clear session criteria.
      }
      currentView.searchResultsView.isSearchTriggered = false;
      currentView.searchResults.reset();
    });
  },
  /**
   * Get the id of the criteria.
   * @returns {string}
   * @override
   */
  getSessionKey: function getSessionKeySearchView() {
    var hash = CoreView.prototype.getSessionKey.call(this);
    if (this.opts.criteriaId !== undefined) {
      hash += this.opts.criteriaId;
    }
    return hash;
  },
  /**
   * Render function  by default call the getRenderData and inject it into the view dom element.
   * @param options
   * @returns {SearchView}
   * @override
   */
  render: function renderSearchView(options) {
    options = options || {};
    CoreView.prototype.render.call(this, options);
    this.$el.html(this.template(_.extend({
      isMoreCriteria: this.isMoreCriteria
    }, this.getRenderData())));
    $(this.resultsSelector, this.$el).html(this.searchResultsView.render().el);
    return this;
  },
  /**
   * Process post rendering logic.
   * @override
   */
  afterRender: function postRenderSearchView() {
    CoreView.prototype.afterRender.call(this);
    $('.collapse', this.$el).collapse('show');
  }
});

module.exports = SearchView;