// Generated by CoffeeScript 1.6.2
(function() {
  var ArgumentInvalidException, ArgumentNullException, CustomException, DependencyException, NotImplementedException,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CustomException = (function() {
    function CustomException(name, message, options) {
      this.name = name;
      this.message = message;
      this.options = options;
    }

    CustomException.prototype.log = function() {
      return console.log("name", this.name, "message", this.message, "options", this.options);
    };

    return CustomException;

  })();

  NotImplementedException = (function(_super) {
    __extends(NotImplementedException, _super);

    function NotImplementedException(message, options) {
      NotImplementedException.__super__.constructor.call(this, "NotImplementedException", message, options);
    }

    return NotImplementedException;

  })(CustomException);

  ArgumentNullException = (function(_super) {
    __extends(ArgumentNullException, _super);

    function ArgumentNullException(message) {
      ArgumentNullException.__super__.constructor.call(this, "ArgumentNull", message);
    }

    return ArgumentNullException;

  })(CustomException);

  ArgumentInvalidException = (function(_super) {
    __extends(ArgumentInvalidException, _super);

    function ArgumentInvalidException(message, options) {
      ArgumentInvalidException.__super__.constructor.call(this, "ArgumentInvalidException", message, options);
    }

    return ArgumentInvalidException;

  })(CustomException);

  DependencyException = (function(_super) {
    __extends(DependencyException, _super);

    function DependencyException(message) {
      DependencyException.__super__.constructor.call(this, "DependencyException", message);
    }

    return DependencyException;

  })(CustomException);

  module.exports = {
    CustomException: CustomException,
    NotImplementedException: NotImplementedException,
    ArgumentNullException: ArgumentNullException,
    ArgumentInvalidException: ArgumentInvalidException
  };

}).call(this);
