// Generated by CoffeeScript 1.6.2
(function() {
  var Model, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = Model = (function(_super) {
    __extends(Model, _super);

    function Model() {
      _ref = Model.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Model.prototype.unsetErrors = function() {
      return this.unset('errors', {
        silent: true
      });
    };

    Model.prototype.setErrors = function(errors) {
      if (errors != null) {
        return this.set({
          'errors': errors
        });
      }
    };

    Model.prototype.metadatas = {
      papa: {
        "domain": "DO_TEXTE_50",
        "required": true
      }
    };

    Model.prototype.modelName = void 0;

    Model.prototype.labels = {
      papa: "model.papa"
    };

    Model.prototype.toJSON = function() {
      var jsonModel;

      jsonModel = Model.__super__.toJSON.call(this);
      jsonModel.metadatas = this.metadatas;
      jsonModel.modelName = this.modelName;
      jsonModel.papa = 'singe';
      return jsonModel;
    };

    return Model;

  })(Backbone.Model);

}).call(this);
